import React, { useState } from 'react';
import { AgentAvatar } from '../ui/AgentAvatar';
import MoreHorizIcon from '@mui/icons-material/MoreHoriz';

export interface UIReviewGateProps {
    projectName: string;
    version: string;
    onApprove: () => void;
    onRequestChanges: (feedback: string) => void;
}

export const UIReviewGate: React.FC<UIReviewGateProps> = ({
    projectName,
    version,
    onApprove,
    onRequestChanges,
}) => {
    const [feedback, setFeedback] = useState('');
    const [logs, setLogs] = useState([
        { author: 'Builder', message: 'UI Generated', time: '10:32 AM', color: 'bg-emerald-400' },
        { author: 'User', message: 'Assigned Review', time: '10:35 AM', color: 'bg-slate-500' }
    ]);

    const handleRequestChanges = () => {
        if (feedback.trim()) {
            onRequestChanges(feedback);

            // Optimistically update logs for demo purposes
            setLogs([...logs, {
                author: 'User',
                message: `Requested Revisions`,
                time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
                color: 'bg-sky-500'
            }]);
            setFeedback('');
        }
    };

    return (
        <div className="w-full max-w-sm mx-auto relative pt-12">
            {/* Main Floating Card */}
            <div className="relative bg-slate-950/85 backdrop-blur-2xl rounded-2xl p-6 pt-10 shadow-2xl ring-1 ring-white/10 flex flex-col gap-5">

                {/* Overlapping Avatar */}
                <div className="absolute -top-10 left-1/2 -translate-x-1/2 flex flex-col items-center">
                    <div className="relative">
                        {/* Glow effect */}
                        <div className="absolute -inset-2 bg-emerald-500/30 blur-xl rounded-full"></div>
                        <AgentAvatar
                            role="builder"
                            size={72}
                            sx={{ border: '2px solid rgba(255,255,255,0.1)' }}
                        />
                    </div>
                </div>

                {/* Header Content */}
                <div className="flex justify-between absolute top-4 right-4">
                    <button className="text-slate-500 hover:text-white transition-colors">
                        <MoreHorizIcon />
                    </button>
                </div>

                <div className="flex flex-col items-center text-center mt-2">
                    <span className="text-[10px] text-slate-500 font-bold tracking-widest uppercase mb-1">Builder</span>
                    <h3 className="text-white text-lg font-bold">Nanobanana</h3>
                    <span className="text-xs text-slate-400">Lead AI Builder | Systemst female engineer</span>
                </div>

                <div className="h-px w-full bg-gradient-to-r from-transparent via-white/10 to-transparent my-2"></div>

                {/* Context Info */}
                <div className="flex flex-col items-start">
                    <p className="text-sm text-slate-300">Reviewing: <span className="text-white font-semibold">{projectName}</span> |</p>
                    <p className="text-sm text-slate-300">Version: <span className="text-white font-semibold">{version}</span> (Generated by AI)</p>
                </div>

                {/* Actions */}
                <div className="flex flex-col gap-3 mt-2">
                    <button
                        onClick={onApprove}
                        className="w-full py-3.5 rounded-xl font-bold text-white bg-gradient-to-r from-emerald-400 to-sky-500 hover:from-emerald-300 hover:to-sky-400 shadow-[0_0_20px_rgba(52,211,153,0.3)] transition-all hover:shadow-[0_0_30px_rgba(52,211,153,0.5)]"
                    >
                        Approve & Deploy UI
                    </button>

                    <button
                        onClick={handleRequestChanges}
                        disabled={!feedback.trim()}
                        className="w-full py-3.5 rounded-xl font-semibold text-white bg-slate-900/50 border border-white/20 hover:bg-slate-800 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
                    >
                        Request Design Changes
                    </button>
                </div>

                {/* Feedback Input */}
                <div className="flex flex-col gap-2 mt-2">
                    <span className="text-xs text-slate-400 font-bold uppercase tracking-wider">Feedback & Revisions (Optional)</span>
                    <textarea
                        rows={3}
                        placeholder="Enter your notes, requests, or comments here..."
                        value={feedback}
                        onChange={(e) => setFeedback(e.target.value)}
                        className="w-full bg-slate-900/60 border border-slate-700 rounded-xl p-3 text-sm text-white focus:outline-none focus:border-sky-500/50 resize-none placeholder-slate-600 transition-colors"
                    />
                </div>

                {/* Activity Log */}
                <div className="flex flex-col gap-3 mt-3">
                    <span className="text-xs text-slate-400 font-bold uppercase tracking-wider">Activity Log</span>
                    <div className="flex flex-col gap-2">
                        {logs.map((log, index) => (
                            <div key={index} className="flex items-start gap-3 w-full">
                                <div className={`w-2 h-2 rounded-full mt-1.5 flex-shrink-0 ${log.color}`}></div>
                                <div className="flex flex-col flex-1">
                                    <div className="flex justify-between items-baseline w-full">
                                        <span className="text-xs font-bold text-white">{log.author}: </span>
                                        <span className="text-[10px] text-slate-500 whitespace-nowrap">{log.time}</span>
                                    </div>
                                    <span className="text-xs text-slate-400">{log.message}</span>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>

            </div>
        </div>
    );
};
